name: flutter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
    sdk: ^3.5.0
    flutter: '>=3.24.0'

dependencies:
    bloc: ^8.1.4
    dartz: ^0.10.1
    dio: ^5.9.0
    equatable: ^2.0.7
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.6
    flutter_localizations:
        sdk: flutter
    flutter_modular: ^6.4.1
    intl: ^0.20.2
    shared_preferences: ^2.5.3

dev_dependencies:
    build_runner: 2.9.0
    flutter_gen_runner:
    bloc_test: ^9.1.7
    flutter_test:
        sdk: flutter
    mocktail: ^1.0.4
    very_good_analysis: ^10.0.0
    flutter_gen: ^5.12.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - .env.development
        - .env.staging
        - .env.production
        - assets/images/

flutter_gen:
    output: lib/gen/
    assets:
        exclude:
            - .env.*
            - assets/.gitkeep
